#!/usr/bin/python3

import amulet
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('logstash', 'cs:xenial/logstash')
        self.d.add('filebeat')
        self.d.relate('filebeat:beats-host', 'ubuntu:juju-info')
        self.d.relate('filebeat:logstash', 'logstash:beat')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.logstash = self.d.sentry['logstash'][0]
        self.filebeat = self.d.sentry['filebeat'][0]

    def test_logstash_host_in_templating(self):
        stash_address = self.logstash.relation('beat', 'filebeat:logstash')['private-address']  # noqa
        config = self.filebeat.file_contents('/etc/filebeat/filebeat.yml')
        self.assertTrue(stash_address in config)


if __name__ == "__main__":
    unittest.main()
