#!/usr/bin/python3

import amulet
import unittest
import time


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('elasticsearch', 'cs:xenial/elasticsearch')
        self.d.add('filebeat')
        self.d.relate('filebeat:beats-host', 'ubuntu:juju-info')
        self.d.relate('filebeat:elasticsearch', 'elasticsearch:client')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.elasticsearch = self.d.sentry['elasticsearch'][0]
        self.filebeat = self.d.sentry['filebeat'][0]

    def test_elasticsearch_host_in_templating(self):
        es_address = self.elasticsearch.relation('client', 'filebeat:elasticsearch')['private-address']  # noqa
        config = self.filebeat.file_contents('/etc/filebeat/filebeat.yml')
        self.assertTrue(es_address in config)

    def test_config_options(self):
        self.d.configure('filebeat',
                         {'logpath': '/var/log/*.log /tmp/amulet.log',
                          'harvester_buffer_size': '9999',
                          'max_bytes': '10485761'})
        self.d.sentry.wait()
        # Changing the config variables just sets a "needs rendering" state.
        # The actual file is updated later so we need to wait a bit.... :(
        time.sleep(20)
        config = self.filebeat.file_contents('/etc/filebeat/filebeat.yml')
        self.assertTrue('/tmp/amulet.log' in config)
        self.assertTrue('9999' in config)
        self.assertTrue('10485761' in config)


if __name__ == "__main__":
    unittest.main()
