#!/usr/bin/python3

import amulet
import time
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('filebeat')
        self.d.relate('filebeat:beats-host', 'ubuntu:juju-info')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.filebeat = self.d.sentry['filebeat'][0]

    def test_logstash_host_in_templating(self):
        logstash_host = '192.168.0.1:5044'
        self.d.configure('filebeat', {'logstash_hosts': logstash_host})
        self.d.sentry.wait()

        # Changing the config variables just sets a "needs rendering" state.
        # The actual file is updated later so we need to wait a bit.... :(
        time.sleep(20)
        config = self.filebeat.file_contents('/etc/filebeat/filebeat.yml')
        self.assertTrue(logstash_host in config)


if __name__ == "__main__":
    unittest.main()
