#!/usr/bin/python3

import amulet
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('kafka', 'cs:xenial/kafka')
        self.d.add('zookeeper', 'cs:xenial/zookeeper')
        self.d.add('filebeat')
        self.d.relate('kafka:zookeeper', 'zookeeper:zookeeper')
        self.d.relate('filebeat:beats-host', 'ubuntu:juju-info')
        self.d.relate('filebeat:kafka', 'kafka:client')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.kafka = self.d.sentry['kafka'][0]
        self.filebeat = self.d.sentry['filebeat'][0]

    def test_kafka_host_in_templating(self):
        kafka_address = self.kafka.relation('client', 'filebeat:kafka')['private-address']  # noqa
        config = self.filebeat.file_contents('/etc/filebeat/filebeat.yml')
        self.assertTrue(kafka_address in config)


if __name__ == "__main__":
    unittest.main()
