#!/usr/bin/python3

import amulet
import time
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment(series='xenial')
        self.d.add('ubuntu', 'cs:xenial/ubuntu')
        self.d.add('filebeat')
        self.d.relate('filebeat:beats-host', 'ubuntu:juju-info')

        self.d.setup(timeout=1200)
        self.d.sentry.wait()

        self.filebeat = self.d.sentry['filebeat'][0]

    def test_invalid_reinstall(self):
        uuid = self.filebeat.run_action('reinstall')
        result = self.d.action_fetch(uuid, full_output=True)
        # action status=completed on success; make sure we failed
        if (result['status'] != "failed"):
            self.fail('Filebeat reinstall should have failed: %s' % result)

    def test_valid_reinstall(self):
        apt_repo = 'deb https://artifacts.elastic.co/packages/6.x/apt stable main'
        self.d.configure('filebeat', {'install_sources': apt_repo})
        self.d.sentry.wait()

        # Wait for the config changed hook to settle
        time.sleep(20)

        # Run the action
        uuid = self.filebeat.run_action('reinstall')
        result = self.d.action_fetch(uuid, full_output=True)
        # action status=completed on success
        if (result['status'] != "completed"):
            self.fail('Filebeat reinstall failed: %s' % result)


if __name__ == "__main__":
    unittest.main()
